### ISSUE TITLE
FYI: Restic now has built-in VSS support

### ISSUE THREAD

**Issue by rawtaz** [kmwoley/restic-windows-backup#23]
PR https://github.com/restic/restic/pull/2274 was merged into restic's master branch today, so the next release of restic will have built-in support for Windows VSS, enabled by the `--use-fs-snapshot` option to the `backup` command. Until the next release, one can try it using the latest master build from https://beta.restic.net/?sort=time&order=desc . I'm just noting this here as information. I guess that at some point this wrapper software will want to make use of it, or maybe not :)

**Comment by kmwoley** [comment]
Agreed. I’m following that issue and the merge. After it is released, I’ll
do some testing. I’d very much like to adopt it vs. using this script to
manage VSS.

**Comment by rawtaz** [comment]
Cool. For housekeeping reasons I'll just go ahead and close this issue, as there's nothing to track. Unless you want to keep it open of course, but then you can just re-open it :) Thanks!

**Comment by kmwoley** [comment]
@rawtaz FYI, I got this implemented and tested. Please let me know if you have any issues. 
Note that the `local.exclude` and 'windows.exclude` files may need to be changed due to no longer relying upon creating a `resticVSS` directory. 
Also, the way the script was creating the backup set directories led to some "snapshot inflation" since Restic groups snapshots by host & folders when doing a `forget`. If you adopt the new config change to `--group-by host` when doing a `forget` that should resolve that issue for any existing repositories.

Cheers!
